### ISSUE TITLE
HealthCheck action

### ISSUE THREAD

**Issue by eric239** [schema-repo/schema-repo#15]
It will be useful to have a simple `ping` / health check action (e.g. `/ping`) (note that I'm considering the two terms equivalent). Something that a client can use to make sure it connected to the live server prior to calling (or between calling) the business actions.

This can be further enhanced to support `cluster ID` concept.

See [this thread for reference/context](https://groups.google.com/forum/#!topic/schema-repo/GOMO9PMWFtc)

**Comment by FelixGV** [comment]
This has been completed. Closing. Thanks for your contribution @eric239 !
