### ISSUE TITLE
HTML view of the repo / browsing

### ISSUE THREAD

**Issue by eric239** [schema-repo/schema-repo#27]
Now that `RESTRepository` already supports multiple views (plain text + JSON) it won't be hard to add HTML support as well. This will allow ad-hoc browsing of subjects & schemas by using one's browser directly.

To make the code cleaner, the idea is to define a `Renderer` interface with methods like `renderSubjects`, `renderSchemas`, etc) and allow implementations for different content types to be registered as properties (with appropriate defaults). The code in `RESTRepository` will simply look up an impl based on the effective content type (Accepts header). That logic will be lifted into a single method.

A template engine will be used to avoid polluting the java code with any HTML tags. The choices are plentiful. At this point the following three are being considered:
* [Velocity](http://velocity.apache.org/)
* [Freemarker](http://freemarker.org/)
* [HTTL](http://httl.github.io/en/)

The first two are fairly simple and well-known, very stable veteran engines.
HTTL syntactically very close, appears to be more lightweight but doesn't appear to be actively developed (last release in '13, plenty of open issues).
Other engines out there (Jade, StringTemplate, etc.) appear to be an overkill.

**Comment by FelixGV** [comment]
Hi @eric239,

Thanks for starting this discussion. Your proposition of a Renderer interface sounds good. Making it pluggable would even allow users to develop and contribute their own renderers easily, which is not a must, but nice to have.

Regarding template engines, I have no personal experience with any of those you mentioned, so I can't really comment for now. The template engine should add a new dependency only to the server artifact, so I don't have much concern with the choice. Please keep us posted if/when you select one (:

Thanks!

-F

**Comment by FelixGV** [comment]
@eric239,

Does the Jersey version affect your plans regarding this? And conversely, does the JDK version affect your plans (later version of Jersey 2.x depend on Java 7)? Please mention it in Issue #34 if that's the case.

Thanks (:

-F

**Comment by eric239** [comment]
@FelixGV "no" to both questions. The code (which I'm actually about to release tonight) is very simple and doesn't use any "advanced" jersey or language features. As discussed in the past, from my point of view it's not "why to upgrade to JDK7" but rather "why not to upgrade" (to which point you had some cases of still-on-jdk6 orgs)

**Comment by FelixGV** [comment]
Great! Definitely looking forward to that :D !

**Comment by teebo** [comment]
I wrote a small NodeJS application that uses the schema-repo and displays the schemas registered in the repo. 
It's currently very basic but could be easily improved. 
If you are interested, feel free to test it :) : 
https://github.com/teebo/schema-repo-frontend
Feedbacks are welcome!

**Comment by eric239** [comment]
@teebo I tried running your app against my current branch (PR #35 ) and navigating browser to `http://localhost:8082` just hangs. I see this in the node's console:
```
GET / /
GET / /
GET / /
```
And this in my schema-repo server console:
```
10:52:46 INFO  [org.schemarepo.server.RESTRepository    ] No renderer configured for media type */*, defaulting to the renderer for text/plain
10:52:46 INFO  [org.schemarepo.server.RESTRepository    ] No renderer configured for media type null, defaulting to the renderer for text/plain
10:54:46 INFO  [org.schemarepo.server.RESTRepository    ] No renderer configured for media type */*, defaulting to the renderer for text/plain
10:54:46 INFO  [org.schemarepo.server.RESTRepository    ] No renderer configured for media type null, defaulting to the renderer for text/plain
10:56:52 INFO  [org.schemarepo.server.RESTRepository    ] No renderer configured for media type */*, defaulting to the renderer for text/plain
10:56:52 INFO  [org.schemarepo.server.RESTRepository    ] No renderer configured for media type null, defaulting to the renderer for text/plain
```
But the repo looks fine: `curl -XGET -H 'Accept:*/*' localhost:2876/schema-repo/` yields my test subject in plain text.

**Comment by teebo** [comment]
@eric239 Ok, thanks for the feedback, strange... I was primarily using the [schema-repo-bundle-0.1.2-withdeps.jar](https://oss.sonatype.org/content/repositories/releases/org/schemarepo/schema-repo-bundle/0.1.2/) but, for me, it's also working with your branch. 

I just changed the "Accept" header in order to accept only text/plain media types. 

Maybe you could try to get `http://localhost:8082/schemas/ASubject` in order to see if it's only the page that lists all subjects that fails.

**Comment by eric239** [comment]
I will. Also note that I've been trying that on windows. Have you tried on
Linux / OSX only?

**Comment by teebo** [comment]
Ok I just tried on windows and, effectively, it's not working. Apparently there are some differences on how data is returned: 
`curl -X GET http://localhost:2876/schema-repo/test/latest` :
* on windows: `0    '<type:record,name:Test,namespace:com.example.test ...`
* on unix: `0    <"type":"record","name":"Test","namespace":"com.example.test" ...`

Therefore JSON.parse() and JSON.stringify() seem to behave a bit differently. I'll see if I can find a quick fix this week.

**Comment by FelixGV** [comment]
It also seems to not be working on OS X... I'm getting:

```
GET / /

undefined:1
schema literal for this subject
^
SyntaxError: Unexpected token s
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/some/path/code/schema-repo-frontend/models/schemas.js:22:23)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at IncomingMessage.Readable.push (_stream_readable.js:128:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:143:22)
```

Shouldn't Node/V8 be portable...? Oh well...! Looking forward to seeing what you have done (: ...

**Comment by teebo** [comment]
Sorry about that... It's a prototype and quite hard to test all possible configurations.

I simplified a bit the code that displays the list of subjects. Now only the subject name is displayed (before I also got the version number and the "doc" field of the schema)
If it's still not working please try to get a specific subject:
`http://localhost:8082/schemas/ASubject`

Obviously be sure that your repo contains at least one subject with one schema :)

**Comment by teebo** [comment]
Oops I forgot to say that, currently, it is designed to work only with avro schemas :/

**Comment by FelixGV** [comment]
Ah I see! Fair enough.

**Comment by FelixGV** [comment]
Your fix is merged into master (:

Reference:
* Main issue: #27 
* Work in progress PR: #35 
* Final PR: #40 

Thanks a lot @eric239 !
