### ISSUE TITLE
Support a list of "Default Subject Validators"

### ISSUE THREAD

**Issue by thunderstumpges** [schema-repo/schema-repo#38]
Currently in order to do vallidation on a subject, the subject must have been created with the correct subject configuration setting (`"schema-repo.validator.validators"`). It would be really useful to be able to set a global configuration to set the default list of validators to use if this setting is not present in the Subject Config.

Please review, and let me know if there's a different way you'd like it done. I'm starting on this in our fork, but would be glad to tweak it for the official repo.

Proposed implementation (that I am starting work on):

1. Create new global config `String DEFAULT_SUBJECT_VALIDATORS = VALIDATION_PREFIX + "default.validators";` 
    which is (`"schema-repo.validation.default.validators"`)
    a) value of this is a comma separated list of validator names to apply to all subjects that 
        don't explicitly specify a setting
2. In AbstractBackendRepository extend the protected constructor to contain this string list of names.
3. In the concrete repositories, configure the constructor to receive this named config and pass along
4. When AbstractBackendRepository creates new validatingSubject, send the list of default subject validators to it.
5. If there is NO setting for validators in SubjectConfig, then ValidatingSubject will use the default list.
    a) An existing key with empty value in SubjectConfig should *not* use the defaults as this would 
        mean to use "no validators"

**Comment by FelixGV** [comment]
Thanks for opening a discussion on this. I think it will be very useful.

I think what you're suggesting can work, but isn't it slightly annoying that every extension of ```AbstractBackendRepository``` would need to pass this new parameter in?

Can we instead make the logic of handling default validators part of the ```ValidatorFactory```? I believe this could be achieved by adding a new ```@Named``` parameter to ```ConfigModule#provideValidatorFactory```. Then, the logic of when to choose the default versus "no validators" can be done entirely in the ```ValidatorFactory``` or in the ```ValidatorFactory``` + ```Subject.validatingSubject```. This approach means there is no requirement to do the right thing from the ```AbstractBackendRepository``` implementor.

What do you think?

**Comment by thunderstumpges** [comment]
Yeah, good call, I think that will work. I'll try that.

**Comment by thunderstumpges** [comment]
Ok, that was definitely cleaner. No logic needing to change in the Repository at all. I have pushed this change to [our fork](https://github.com/ntent-ad/schema-repo/commit/0070dac23e3d3b8ef4185bb08d48f07f050540c7), I can create a pull-request or patch if you would like. 

Thanks,
Thunder

**Comment by thunderstumpges** [comment]
One thing I should point out is that there has been a semantic change to whether one SubjectConfig is the same as another. 

Based on number 5 in the original Issue, if an empty list of validators is set explicityly in the SubjectConfig, then that needs to mean "explicitly no validators". This is new, as before, setting an empty or null list of validators in SubjectConfig was a no-op. 

See the [changes in TestSubjectConfig](https://github.com/ntent-ad/schema-repo/commit/0070dac23e3d3b8ef4185bb08d48f07f050540c7?diff=split#diff-5)

**Comment by FelixGV** [comment]
Great!

Yeah, I do think that would be good to have as a PR (:

Can you mention this Issue #38 in your PR / commit message, so we have traceability back to this discussion?

Thanks @thunderstumpges !

**Comment by thunderstumpges** [comment]
[PR created](https://github.com/schema-repo/schema-repo/pull/39).

Thanks.

**Comment by FelixGV** [comment]
Closed as part of PR #39. Thanks!
