### ISSUE TITLE
Strongly-typed client library

### ISSUE THREAD

**Issue by FelixGV** [schema-repo/schema-repo#9]
The schema-repo project should provide first-class support for a strongly-typed client library (i.e.: not Stringly-typed).

This client library should convert schema literals to usable schema instances (such as instances of org.apache.avro.Schema) and cache those instances locally. It should also provide strong typing for schema IDs, in case people want to use Integer IDs in their code.

This library should be implemented in a generic manner so that other (non-Avro) serialization schemes can be supported easily in the future.

Furthermore, clients probably aren't interested in dealing with SchemaEntry instances and so on. These are implementation details on the server-side and should not trickle out into userland. The client-facing APIs should be as simple as possible.

**Comment by elad** [comment]
Hey,

Any estimate when will this feature be released? Even 0.1.3-SNAPSHOT works fine and it would be great if there'd be a way to grab that from a repository rather than copying the typed repository code.

**Comment by FelixGV** [comment]
Makes sense. I've cut release 0.1.3 from the current master and pushed it to the SonaType Repository. It should be synced to Maven Central within the next 2 hours...

Thanks.

**Comment by elad** [comment]
Hi,

Thanks for the prompt response. I must be missing something though because I don't see [TypedSchemaRepository.java](https://github.com/schema-repo/schema-repo/blob/master/api/src/main/java/org/schemarepo/api/TypedSchemaRepository.java) in the jar file.

I downloaded [schema-repo-common-0.1.3.jar](https://search.maven.org/#artifactdetails%7Corg.schemarepo%7Cschema-repo-common%7C0.1.3%7Cjar) and ran `jar tf` to verify the file's not there:

```
$ jar tf schema-repo-common-0.1.3.jar | grep Typed
$
```

What am I doing wrong?

**Comment by FelixGV** [comment]
The strongly-typed APIs are in a new maven module called api. If you pull
just that, it should transitively pull common as well. If you're working
with Avro, you may also want to pulp the avro module to get the converter
from there.

The granularity of the modules may be overkill. Feel free to comment on
that if you have an opinion.

-F

**Comment by elad** [comment]
What's the benefit of separating them? Unless there's a very good reason to do so I'd vote to keep them in one package. But I'd suggest to poll others who use schema-repo for their opinion as well because my use case may not be the common one.

**Comment by FelixGV** [comment]
Thanks for the comment.

The reasons I can think of for the separation are the following:
* The api code is not used in the server-side, nor is it used by any of the "legacy users" of the schema-repo (people using AVRO-1124)...
* The api code pulls in guava as a dependency, which personally I don't think is a very big deal, but I know some people want to keep their dependencies as minimal as possible (though presumably they could also exclude this transitive dependency in their own build if they really cared).

That being said, I agree that fewer modules is nice and simpler.

There is a bundle module which just gives you everything, including transitive dependencies, in case you don't care about trimming down dependencies. I'm not sure if that's 100% satisfactory, but that's the current state...

**Comment by elad** [comment]
The reasons you brought up make a good case for modules, I agree. I'll pull in the api module and/or use the bundle. Thanks! :)
